fix newline issue

diff --git a/04/hatten4-1 b/04/hatten4-1
--- a/04/hatten4-1
+++ b/04/hatten4-1
@@ -1,5 +1,7 @@
-#!/bin/sh
+#!/bin/bash
+. ../util.sh --source-only
 
+shpath=$PWD
 cd $(dirname $0)
 path=${1:-../src}
 cd $path
@@ -12,24 +14,54 @@ if [ $n_file = 0 ]; then
   exit 1
 fi
 
+# rm only exec files
+efile=`ls $tfile* | grep -Ev "*.c"`
+n_efile=`ls -1 $tfile* 2>/dev/null | grep -Ev "*.c" | wc -l`
+if [ $n_efile -gt 0 ]; then
+  echo "-- removed --------------"
+  echo $efile
+  echo "-------------------------"
+  rm $efile
+fi
+
+echo -e "\n=============================" \
+        "\n* Input 5 people scores. Print average score." \
+        "\n  Then print scores over ave and scores under ave separately.\n" \
+        "\n* Use array to store input scores." \
+        "\n============================="
+
+echo -e "\n==========Test case==========" \
+        "\n 10 80 38 60 90"\
+        "\n 10 0 5 3 9"\
+        "\n 200 90 85 83 89 90"\
+        "\n 60 59 61 0 0"\
+        "\n============================="
+
+fail=()
 for cfile in $tfile*.c
 do
   filename=`basename $cfile .c`
-  echo -e "\n============================="
+  printf "\n%s\n" "$pad"
   echo "$filename"
-  echo "----------------------------"
-  gcc "$PWD/$cfile" -o "$PWD/$filename"
-  echo 10 80 38 60 90 | $PWD/$filename
+  printf "%s\n" "$line"
+  gcc "$PWD/$cfile" -o "$PWD/$filename" 2>> $shpath/err.log
+  if [ $? -ne 0 ]; then
+    fail+=( $cfile )
+    echo -e "Compile filed." \
+            "\n============================="
+    continue
+  fi
+  echo -e "10\n80\n38\n60\n90\n" | $PWD/$filename
   echo -e "expected\n" \
           "Ave       : 55.6\n" \
           "Over  Ave : 80 60 90\n" \
           "Under Ave : 10 38\n"
-  echo 10 0 5 3 9 | $PWD/$filename
+  echo -e "10\n0\n5\n3\n9\n" | $PWD/$filename
   echo -e "expected\n" \
           "Ave       : 5.4\n" \
           "Over  Ave : 10 9\n" \
           "Under Ave : 0 5 3\n"
-  echo 200 90 85 83 89 90 | $PWD/$filename
+  echo -e "200\n90\n85\n83\n89\n90\n" | $PWD/$filename
   echo -e "expected\n" \
           "(if 200 included)\n" \
           "Ave       : 109.4\n" \
@@ -40,18 +72,20 @@ do
           "Ave       : 87.4\n" \
           "Over  Ave : 90 89 90\n" \
           "Under Ave : 85 83\n"
-  echo 60 59 61 0 0 | $PWD/$filename
+  echo -e "60\n59\n61\n0\n0\n" | $PWD/$filename
   echo -e "expected\n" \
           "Ave       : 36.0\n" \
           "Over  Ave : 60 59 61\n" \
           "Under Ave : 0 0"
-  echo -e "============================="
+  printf "%s\n" "$pad"
 done
 
 n_efile=`ls $tfile* | grep -Ev "*.c" | wc -l`
-
-echo -e "\n========compile check========" \
+echo -e "\n========Compile Check========" \
         "\nSrc File      : $n_efile" \
         "\nExecute File  : $n_file" \
         "\nCompile Error : $(($n_file-$n_efile))" \
         "\n============================="
+
+print_files fail[@] "Failed files"
+
diff --git a/04/hatten4-2 b/04/hatten4-2
--- a/04/hatten4-2
+++ b/04/hatten4-2
@@ -1,5 +1,7 @@
-#!/bin/sh
+#!/bin/bash
+. ../util.sh --source-only
 
+shpath=$PWD
 cd $(dirname $0)
 path=${1:-../src}
 cd $path
@@ -12,28 +14,59 @@ if [ $n_file = 0 ]; then
   exit 1
 fi
 
+# rm only exec files
+efile=`ls $tfile* | grep -Ev "*.c"`
+n_efile=`ls -1 $tfile* 2>/dev/null | grep -Ev "*.c" | wc -l`
+if [ $n_efile -gt 0 ]; then
+  echo "-- removed --------------"
+  echo $efile
+  echo "-------------------------"
+  rm $efile
+fi
+
+echo -e "\n=============================" \
+        "\n* Input two 2*2 matrices, multiply them and print the result.\n" \
+        "\n* 3 nested for loop is recommended." \
+        "\n============================="
+
+echo -e "\n==========Test case==========" \
+        "\n 1 2 3 4 1 1 1 1"\
+        "\n 2 -1 1 3 1 2 3 4"\
+        "\n -5 -4 4 13 0 5 -3 9"\
+        "\n -5 -4 4 13 0 0 0 0"\
+        "\n============================="
+
+fail=()
 for cfile in $tfile*.c
 do
   filename=`basename $cfile .c`
-  echo -e "\n============================="
+  printf "\n%s\n" "$pad"
   echo "$filename"
-  echo "----------------------------"
-  gcc "$PWD/$cfile" -o "$PWD/$filename"
-  echo 1 2 3 4 1 1 1 1 | $PWD/$filename      # => 3 3 7 7
+  printf "%s\n" "$line"
+  gcc "$PWD/$cfile" -o "$PWD/$filename" 2>> $shpath/err.log
+  if [ $? -ne 0 ]; then
+    fail+=( $cfile )
+    echo -e "Compile failed." \
+            "\n============================="
+    continue
+  fi
+  echo -e "1\n2\n3\n4\n1\n1\n1\n1\n" | $PWD/$filename
   echo -e "expected 3 3 7 7\n"
-  echo 2 -1 1 3 1 2 3 4 | $PWD/$filename     # => -1 0 10 14
+  echo -e "2\n-1\n1\n3\n1\n2\n3\n4\n" | $PWD/$filename
   echo -e "expected -1 0 10 14\n"
-  echo -5 -4 4 13 0 5 -3 9 | $PWD/$filename  # => 12 -61 -39 137
+  echo -e "-5\n-4\n4\n13\n0\n5\n-3\n9\n" | $PWD/$filename
   echo -e "expected 12 -61 -39 137\n"
-  echo -5 -4 4 13 0 0 0 0 | $PWD/$filename
+  echo -e "-5\n-4\n4\n13\n0\n0\n0\n0\n" | $PWD/$filename
   echo -e "expected 0 0 0 0"
-  echo -e "============================="
+  printf "%s\n" "$pad"
 done
 
 n_efile=`ls $tfile* | grep -Ev "*.c" | wc -l`
-
-echo -e "\n========compile check========" \
+echo -e "\n========Compile Check========" \
         "\nSrc File      : $n_file" \
         "\nExecute File  : $n_efile" \
         "\nCompile Error : $(($n_file-$n_efile))" \
         "\n============================="
+
+print_files fail[@] "Failed files"
+
diff --git a/04/hatten4-3 b/04/hatten4-3
--- a/04/hatten4-3
+++ b/04/hatten4-3
@@ -1,5 +1,7 @@
-#!/bin/sh
+#!/bin/bash
+. ../util.sh --source-only
 
+shpath=$PWD
 cd $(dirname $0)
 path=${1:-../src}
 cd $path
@@ -37,32 +39,41 @@ echo -e "\n==========Test case==========" \
         "\n -1 -1 -1 -1 3" \
         "\n============================="
 
+fail=()
 for cfile in $tfile*.c
 do
   filename=`basename $cfile .c`
-  echo -e "\n============================="
+  printf "\n%s\n" "$pad"
   echo "$filename"
-  echo "----------------------------"
-  gcc "$PWD/$cfile" -o "$PWD/$filename"
-  echo 1 2 3 4 1 | $PWD/$filename
+  printf "%s\n" "$line"
+  gcc "$PWD/$cfile" -o "$PWD/$filename" 2>> $shpath/err.log
+  if [ $? -ne 0 ]; then
+    fail+=( $cfile )
+    echo -e "Compile failed." \
+            "\n============================="
+    continue
+  fi
+  echo -e "1\n2\n3\n4\n1\n" | $PWD/$filename
   echo -e "expected 1 2 3 4\n"
-  echo 1 2 3 4 3 | $PWD/$filename
+  echo -e "1\n2\n3\n4\n3\n" | $PWD/$filename
   echo -e "expected 37 54 81 118\n"
-  echo 1 2 3 4 10 | $PWD/$filename
+  echo -e "1\n2\n3\n4\n10\n" | $PWD/$filename
   echo -e "expected 4783807 6972050 10458075 15241882\n"
-  echo -3 2 4 4 2 | $PWD/$filename
+  echo -e "-3\n2\n4\n4\n2\n" | $PWD/$filename
   echo -e "expected 17 2 4 24\n"
-  echo 0 0 0 0 100 | $PWD/$filename
+  echo -e "0\n0\n0\n0\n100\n" | $PWD/$filename
   echo -e "expected 0 0 0 0\n"
-  echo -1 -1 -1 -1 3 | $PWD/$filename
+  echo -e "-1\n-1\n-1\n-1\n3\n" | $PWD/$filename
   echo -e "expected -4 -4 -4 -4"
-  echo -e "============================="
+  printf "%s\n" "$pad"
 done
 
 n_efile=`ls $tfile* | grep -Ev "*.c" | wc -l`
-
-echo -e "\n========compile check========" \
+echo -e "\n========Compile Check========" \
         "\nSrc File      : $n_file" \
         "\nExecute File  : $n_efile" \
         "\nCompile Error : $(($n_file-$n_efile))" \
         "\n============================="
+
+print_files fail[@] "Failed files"
+
diff --git a/04/hatten4-4 b/04/hatten4-4
--- a/04/hatten4-4
+++ b/04/hatten4-4
@@ -1,5 +1,7 @@
-#!/bin/sh
+#!/bin/bash
+. ../util.sh --source-only
 
+shpath=$PWD
 cd $(dirname $0)
 path=${1:-../src}
 cd $path
@@ -37,26 +39,35 @@ echo -e "\n==========Test case==========" \
         "\n1.5 1 6 -1 5 4" \
         "\n============================="
 
+fail=()
 for cfile in $tfile*.c
 do
   filename=`basename $cfile .c`
-  echo -e "\n============================="
+  printf "\n%s\n" "$pad"
   echo "$filename"
-  echo "----------------------------"
-  gcc "$PWD/$cfile" -o "$PWD/$filename"
-  echo 1 2 3 4 5 6 | $PWD/$filename
+  printf "%s\n" "$line"
+  gcc "$PWD/$cfile" -o "$PWD/$filename" 2>> $shpath/err.log
+  if [ $? -ne 0 ]; then
+    fail+=( $cfile )
+    echo -e "Compile failed." \
+            "\n============================="
+    continue
+  fi
+  echo -e "1\n2\n3\n4\n5\n6\n" | $PWD/$filename
   echo -e "expected -4 4.5\n"
-  echo 1 1 1 -1 10 4 | $PWD/$filename
+  echo -e "1\n1\n1\n-1\n10\n4\n" | $PWD/$filename
   echo -e "expected 7 3\n"
-  echo 1.5 1 6 -1 5 4 | $PWD/$filename
+  echo -e "1.5\n1\n6\n-1\n5\n4\n" | $PWD/$filename
   echo -e "expected about 1.2 3.2"
-  echo -e "============================="
+  printf "%s\n" "$pad"
 done
 
 n_efile=`ls $tfile* | grep -Ev "*.c" | wc -l`
-
-echo -e "\n========compile check========" \
+echo -e "\n========Compile Check========" \
         "\nSrc File      : $n_file" \
         "\nExecute File  : $n_efile" \
         "\nCompile Error : $(($n_file-$n_efile))" \
         "\n============================="
+
+print_files fail[@] "Failed files"
+
diff --git a/04/hatten4-5 b/04/hatten4-5
--- a/04/hatten4-5
+++ b/04/hatten4-5
@@ -1,5 +1,7 @@
-#!/bin/sh
+#!/bin/bash
+. ../util.sh --source-only
 
+shpath=$PWD
 cd $(dirname $0)
 path=${1:-../src}
 cd $path
@@ -37,32 +39,41 @@ echo -e "\n==========Test case==========" \
         "\n2" \
         "\n============================="
 
+fail=()
 for cfile in $tfile*.c
 do
   filename=`basename $cfile .c`
-  echo -e "\n============================="
+  printf "\n%s\n" "$pad"
   echo "$filename"
-  echo "----------------------------"
-  gcc "$PWD/$cfile" -o "$PWD/$filename"
-  echo 10 | $PWD/$filename
+  printf "%s\n" "$line"
+  gcc "$PWD/$cfile" -o "$PWD/$filename" 2>> $shpath/err.log
+  if [ $? -ne 0 ]; then
+    fail+=( $cfile )
+    echo -e "Compile failed." \
+            "\n============================="
+    continue
+  fi
+  echo -e "10\n" | $PWD/$filename
   echo -e "expected 1010\n"
-  echo 10000 | $PWD/$filename
+  echo -e "10000\n" | $PWD/$filename
   echo -e "expected 10011100010000\n"
-  echo 70000 65535 | $PWD/$filename
+  echo -e "70000\n65535\n" | $PWD/$filename
   echo -e "expected (10001000101110000) 1111111111111111\n"
-  echo 19 | $PWD/$filename
+  echo -e "19\n" | $PWD/$filename
   echo -e "expected 10011\n"
-  echo 0 1 | $PWD/$filename
+  echo -e "0\n1\n" | $PWD/$filename
   echo -e "expected (0) 1\n"
-  echo 2 | $PWD/$filename
+  echo -e "2\n" | $PWD/$filename
   echo -e "expected 10"
-  echo -e "============================="
+  printf "%s\n" "$pad"
 done
 
 n_efile=`ls $tfile* | grep -Ev "*.c" | wc -l`
-
-echo -e "\n========compile check========" \
+echo -e "\n========Compile Check========" \
         "\nSrc File      : $n_file" \
         "\nExecute File  : $n_efile" \
         "\nCompile Error : $(($n_file-$n_efile))" \
         "\n============================="
+
+print_files fail[@] "Failed files"
+
