use util.sh

diff --git a/06/hatten6-1 b/06/hatten6-1
--- a/06/hatten6-1
+++ b/06/hatten6-1
@@ -1,5 +1,7 @@
-#!/bin/sh
+#!/bin/bash
+. ../util.sh --source-only
 
+shpath=$PWD
 cd $(dirname $0)
 path=${1:-../src}
 cd $path
@@ -36,13 +38,20 @@ echo -e "\n==========Test case==========" \
         "\nthirty-year-old" \
         "\n============================="
 
+fail=()
 for cfile in $tfile*.c
 do
   filename=`basename $cfile .c`
-  echo -e "\n============================="
+  printf "\n%s\n" "$pad"
   echo "$filename"
-  echo "----------------------------"
-  gcc "$PWD/$cfile" -o "$PWD/$filename"
+  printf "%s\n" "$line"
+  gcc "$PWD/$cfile" -o "$PWD/$filename" 2>> $shpath/err.log
+  if [ $? -ne 0 ]; then
+    fail+=( $cfile )
+    echo -e "Compile filed." \
+            "\n============================="
+    continue
+  fi
   echo This is a pen. | $PWD/$filename
   echo -e " expected: 4\n"
   echo Is this a pen? | $PWD/$filename
@@ -55,13 +64,15 @@ do
   echo -e " expected: 1\n"
   echo thirty-year-old | $PWD/$filename
   echo -e " expected: 3\n"
-  echo -e "============================="
+  printf "%s\n" "$pad"
 done
 
 n_efile=`ls $tfile* | grep -Ev "*.c" | wc -l`
-
-echo -e "\n========compile check========" \
+echo -e "\n========Compile check========" \
         "\nSrc File      : $n_file" \
         "\nExecute File  : $n_efile" \
         "\nCompile Error : $(($n_file-$n_efile))" \
         "\n============================="
+
+print_files fail[@] "Failed files"
+
diff --git a/06/hatten6-2 b/06/hatten6-2
--- a/06/hatten6-2
+++ b/06/hatten6-2
@@ -1,5 +1,7 @@
-#!/bin/sh
+#!/bin/bash
+. ../util.sh --source-only
 
+shpath=$PWD
 cd $(dirname $0)
 path=${1:-../src}
 cd $path
@@ -35,13 +37,20 @@ echo -e "\n==========Test case==========" \
         "\nAB 3 -  CD? ? " \
         "\n============================="
 
+fail=()
 for cfile in $tfile*.c
 do
   filename=`basename $cfile .c`
-  echo -e "\n============================="
+  printf "\n%s\n" "$pad"
   echo "$filename"
-  echo "----------------------------"
-  gcc "$PWD/$cfile" -o "$PWD/$filename"
+  printf "%s\n" "$line"
+  gcc "$PWD/$cfile" -o "$PWD/$filename" 2>> $shpath/err.log
+  if [ $? -ne 0 ]; then
+    fail+=( $cfile )
+    echo -e "Compile filed." \
+            "\n============================="
+    continue
+  fi
   echo "Unidentified Flying Object" | $PWD/$filename
   echo -e " expected: UFO\n"
   echo "ABCD" | $PWD/$filename
@@ -54,13 +63,15 @@ do
   echo -e " expected: ABCD\n"
   echo "\nAB 3 -  CD? ? " | $PWD/$filename
   echo -e " expected: ABCD\n"
-  echo -e "============================="
+  printf "%s\n" "$pad"
 done
 
 n_efile=`ls $tfile* | grep -Ev "*.c" | wc -l`
-
-echo -e "\n========compile check========" \
+echo -e "\n========Compile check========" \
         "\nSrc File      : $n_efile" \
         "\nExecute File  : $n_file" \
         "\nCompile Error : $(($n_file-$n_efile))" \
         "\n============================="
+
+print_files fail[@] "Failed files"
+
diff --git a/06/hatten6-4 b/06/hatten6-4
--- a/06/hatten6-4
+++ b/06/hatten6-4
@@ -1,5 +1,7 @@
-#!/bin/sh
+#!/bin/bash
+. ../util.sh --source-only
 
+shpath=$PWD
 cd $(dirname $0)
 path=${1:-../src}
 cd $path
@@ -35,13 +37,21 @@ echo -e "\n==========Test case==========" \
         "\nzvn abcdefg" \
         "\n============================="
 
+fail=()
 for cfile in $tfile*.c
 do
   filename=`basename $cfile .c`
-  echo -e "\n============================="
+  printf "\n%s\n" "$pad"
   echo "$filename"
-  echo "----------------------------"
-  gcc "$PWD/$cfile" -o "$PWD/$filename"
+  printf "%s\n" "$line"
+  gcc "$PWD/$cfile" -o "$PWD/$filename" 2>> $shpath/err.log
+  if [ $? -ne 0 ]; then
+    # fail("${fail[@]}" $cfile)
+    fail+=( $cfile )
+    echo -e "Compile filed." \
+            "\n============================="
+    continue
+  fi
   echo def abcdefg | $PWD/$filename
   echo -e " expected: yes\n"
   echo cef abcefg | $PWD/$filename
@@ -52,13 +62,15 @@ do
   echo -e " expected: no\n"
   echo zvn abcdefg | $PWD/$filename
   echo -e " expected: no\n"
-  echo -e "============================="
+  printf "%s\n" "$pad"
 done
 
 n_efile=`ls $tfile* | grep -Ev "*.c" | wc -l`
-
-echo -e "\n========compile check========" \
+echo -e "\n========Compile check========" \
         "\nSrc File      : $n_file" \
         "\nExecute File  : $n_efile" \
         "\nCompile Error : $(($n_file-$n_efile))" \
         "\n============================="
+
+print_files fail[@] "Failed files"
+
diff --git a/06/kihon6-1 b/06/kihon6-1
--- a/06/kihon6-1
+++ b/06/kihon6-1
@@ -1,4 +1,5 @@
-#!/bin/sh
+#!/bin/bash
+. ../util.sh --source-only
 
 cd $(dirname $0)
 path=${1:-../src}
@@ -33,13 +34,21 @@ echo -e "\n==========Test case==========" \
         "\ninput (<- 1 space at end of the word.)" \
         "\n============================="
 
+fail=()
 for cfile in $tfile*.c
 do
   filename=`basename $cfile .c`
-  echo -e "\n============================="
+  printf "\n%s\n" "$pad"
   echo "$filename"
-  echo "----------------------------"
-  gcc "$PWD/$cfile" -o "$PWD/$filename"
+  printf "%s\n" "$line"
+  gcc "$PWD/$cfile" -o "$PWD/$filename" 2>> $shpath/err.log
+  if [ $? -ne 0 ]; then
+    # fail("${fail[@]}" $cfile)
+    fail+=( $cfile )
+    echo -e "Compile filed." \
+            "\n============================="
+    continue
+  fi
   echo This is a pen. | $PWD/$filename
   echo -e " expected: 14\n"
   echo I think, that is 2 pen. | $PWD/$filename
@@ -48,13 +57,15 @@ do
   echo -e " expected: 5\n"
   echo "input " | $PWD/$filename
   echo -e " expected: 6\n"
-  echo -e "============================="
+  printf "%s\n" "$pad"
 done
 
 n_efile=`ls $tfile* | grep -Ev "*.c" | wc -l`
-
-echo -e "\n========compile check========" \
+echo -e "\n========Compile check========" \
         "\nSrc File      : $n_efile" \
         "\nExecute File  : $n_file" \
         "\nCompile Error : $(($n_file-$n_efile))" \
         "\n============================="
+
+print_files fail[@] "Failed files"
+
