deal with compile error

diff --git a/10/kihon10-1 b/10/kihon10-1
--- a/10/kihon10-1
+++ b/10/kihon10-1
@@ -1,5 +1,6 @@
 #!/bin/sh
 
+shpath=$PWD
 cd $(dirname $0)
 path=${1:-../src}
 cd $path
@@ -16,7 +17,7 @@ fi
 efile=`ls $tfile* | grep -Ev "*.c"`
 n_efile=`ls -1 $tfile* 2>/dev/null | grep -Ev "*.c" | wc -l`
 if [ $n_efile -gt 0 ]; then
-  echo "-- removed --------------"
+  echo "-------- removed --------"
   echo $efile
   echo "-------------------------"
   rm $efile
@@ -34,13 +35,22 @@ echo -e "\n==========Test case==========" \
         "\n 2 asdfg" \
         "\n============================="
 
+fail=()
 for cfile in $tfile*.c
 do
   filename=`basename $cfile .c`
   echo -e "\n============================="
   echo "$filename"
   echo "----------------------------"
-  gcc "$PWD/$cfile" -o "$PWD/$filename"
+  # gcc "$PWD/$cfile" -o "$PWD/$filename" 2>/dev/null
+  gcc "$PWD/$cfile" -o "$PWD/$filename" 2>> $shpath/err.log
+  if [ $? -ne 0 ]; then
+    # fail("${fail[@]}" $cfile)
+    fail+=( $cfile )
+    echo -e "Compile filed." \
+            "\n============================="
+    continue
+  fi
   echo 10 abcde | $PWD/$filename
   echo -e " expected: edcba\n"
   echo 1000 input | $PWD/$filename
@@ -50,10 +60,18 @@ do
   echo -e "============================="
 done
 
-n_efile=`ls $tfile* | grep -Ev "*.c" | wc -l`
+if [ ${#fail[@]} -gt 0 ]; then
+  echo -e "\n\n========Failed files========="
+  for failfile in ${fail[@]}; do
+    echo ${failfile}
+  done
+  echo "============================="
+fi
 
+n_efile=`ls $tfile* | grep -Ev "*.c" | wc -l`
 echo -e "\n========compile check========" \
         "\nSrc File      : $n_file" \
         "\nExecute File  : $n_efile" \
         "\nCompile Error : $(($n_file-$n_efile))" \
         "\n============================="
+
