deal with compile error

diff --git a/08/hatten8-1 b/08/hatten8-1
--- a/08/hatten8-1
+++ b/08/hatten8-1
@@ -36,13 +36,21 @@ echo -e "\n==========Test case==========" \
         "\n -1 -4 -11 0 0 0 0" \
         "\n============================="
 
+fail=()
 for cfile in $tfile*.c
 do
   filename=`basename $cfile .c`
   echo -e "\n============================="
   echo "$filename"
   echo "----------------------------"
-  gcc "$PWD/$cfile" -o "$PWD/$filename"
+  gcc "$PWD/$cfile" -o "$PWD/$filename" 2>> $shpath/err.log
+  if [ $? -ne 0 ]; then
+    # fail("${fail[@]}" $cfile)
+    fail+=( $cfile )
+    echo -e "Compile filed." \
+            "\n============================="
+    continue
+  fi
   echo 5 3 7 0 0 0 0 | $PWD/$filename
   echo -e " expected: 5.0\n"
   echo 10 90 100 0 0 0 0 | $PWD/$filename
@@ -54,8 +62,15 @@ do
   echo -e "============================="
 done
 
-n_efile=`ls $tfile* | grep -Ev "*.c" | wc -l`
+if [ ${#fail[@]} -gt 0 ]; then
+  echo -e "\n\n========Failed files========="
+  for failfile in ${fail[@]}; do
+    echo ${failfile}
+  done
+  echo "============================="
+fi
 
+n_efile=`ls $tfile* | grep -Ev "*.c" | wc -l`
 echo -e "\n========compile check========" \
         "\nSrc File      : $n_file" \
         "\nExecute File  : $n_efile" \
diff --git a/08/hatten8-5 b/08/hatten8-5
--- a/08/hatten8-5
+++ b/08/hatten8-5
@@ -1,5 +1,6 @@
 #!/bin/sh
 
+shpath=$PWD
 cd $(dirname $0)
 path=${1:-../src}
 cd $path
@@ -34,13 +35,20 @@ echo -e "\n==========Test case==========" \
         "\n -10 -2 -100 -20 -4" \
         "\n============================="
 
+fail=()
 for cfile in $tfile*.c
 do
   filename=`basename $cfile .c`
   echo -e "\n============================="
   echo "$filename"
   echo "----------------------------"
-  gcc "$PWD/$cfile" -o "$PWD/$filename"
+  gcc "$PWD/$cfile" -o "$PWD/$filename" 2>> $shpath/err.log
+  if [ $? -ne 0 ]; then
+    fail+=( $cfile )
+    echo -e "Compile filed." \
+            "\n============================="
+    continue
+  fi
   echo "10 50 38 80 60" | $PWD/$filename
   echo -e " expected: 10 38 50 60 80\n"
   echo "0 0 0 0 0" | $PWD/$filename
@@ -52,8 +60,15 @@ do
   echo -e "============================="
 done
 
-n_efile=`ls $tfile* | grep -Ev "*.c" | wc -l`
+if [ ${#fail[@]} -gt 0 ]; then
+  echo -e "\n\n========Failed files========="
+  for failfile in ${fail[@]}; do
+    echo ${failfile}
+  done
+  echo "============================="
+fi
 
+n_efile=`ls $tfile* | grep -Ev "*.c" | wc -l`
 echo -e "\n========compile check========" \
         "\nSrc File      : $n_file" \
         "\nExecute File  : $n_efile" \
diff --git a/08/kihon8-2 b/08/kihon8-2
--- a/08/kihon8-2
+++ b/08/kihon8-2
@@ -1,5 +1,6 @@
 #!/bin/sh
 
+shpath=$PWD
 cd $(dirname $0)
 path=${1:-../src}
 cd $path
@@ -35,13 +36,20 @@ echo -e "\n==========Test case==========" \
         "\n -1 -4 12" \
         "\n============================="
 
+fail=()
 for cfile in $tfile*.c
 do
   filename=`basename $cfile .c`
   echo -e "\n============================="
   echo "$filename"
   echo "----------------------------"
-  gcc "$PWD/$cfile" -o "$PWD/$filename"
+  gcc "$PWD/$cfile" -o "$PWD/$filename" 2>> $shpath/err.log
+  if [ $? -ne 0 ]; then
+    fail+=( $cfile )
+    echo -e "Compile filed." \
+            "\n============================="
+    continue
+  fi
   echo 5 3 7 | $PWD/$filename
   echo -e " expected: 5 3 7\n"
   echo 10 90 100 | $PWD/$filename
@@ -51,8 +59,15 @@ do
   echo -e "============================="
 done
 
-n_efile=`ls $tfile* | grep -Ev "*.c" | wc -l`
+if [ ${#fail[@]} -gt 0 ]; then
+  echo -e "\n\n========Failed files========="
+  for failfile in ${fail[@]}; do
+    echo ${failfile}
+  done
+  echo "============================="
+fi
 
+n_efile=`ls $tfile* | grep -Ev "*.c" | wc -l`
 echo -e "\n========compile check========" \
         "\nSrc File      : $n_file" \
         "\nExecute File  : $n_efile" \
diff --git a/09/hatten9-1 b/09/hatten9-1
--- a/09/hatten9-1
+++ b/09/hatten9-1
@@ -1,5 +1,6 @@
 #!/bin/sh
 
+shpath=$PWD
 cd $(dirname $0)
 path=${1:-../src}
 cd $path
@@ -48,13 +49,20 @@ echo -e "\n==========Test case==========" \
         "\n Taro 176 64.5 Jiro 165 55.5 Saburo 168 70.0 Jiro" \
         "\n============================="
 
+fail=()
 for cfile in $tfile*.c
 do
   filename=`basename $cfile .c`
   echo -e "\n============================="
   echo "$filename"
   echo "----------------------------"
-  gcc "$PWD/$cfile" -o "$PWD/$filename"
+  gcc "$PWD/$cfile" -o "$PWD/$filename" 2>> $shpath/err.log
+  if [ $? -ne 0 ]; then
+    fail+=( $cfile )
+    echo -e "Compile filed." \
+            "\n============================="
+    continue
+  fi
   echo Taro 176 64.5 Jiro 165 55.5 Saburo 168 70.0 Jiro | $PWD/$filename
   echo -e " expected: Jiro, BMI is 20.385675.\n"
   echo Taro 176 64.5 Jiro 165 55.5 Saburo 168 70.0 Jiro | $PWD/$filename
@@ -64,8 +72,15 @@ do
   echo -e "============================="
 done
 
-n_efile=`ls $tfile* | grep -Ev "*.c" | wc -l`
+if [ ${#fail[@]} -gt 0 ]; then
+  echo -e "\n\n========Failed files========="
+  for failfile in ${fail[@]}; do
+    echo ${failfile}
+  done
+  echo "============================="
+fi
 
+n_efile=`ls $tfile* | grep -Ev "*.c" | wc -l`
 echo -e "\n========compile check========" \
         "\nSrc File      : $n_efile" \
         "\nExecute File  : $n_file" \
diff --git a/09/hatten9-2 b/09/hatten9-2
--- a/09/hatten9-2
+++ b/09/hatten9-2
@@ -1,5 +1,6 @@
 #!/bin/sh
 
+shpath=$PWD
 cd $(dirname $0)
 path=${1:-../src}
 cd $path
@@ -43,13 +44,20 @@ echo -e "\n==========Test case==========" \
         "\n 9 4 -9 4" \
         "\n============================="
 
+fail=()
 for cfile in $tfile*.c
 do
   filename=`basename $cfile .c`
   echo -e "\n============================="
   echo "$filename"
   echo "----------------------------"
-  gcc "$PWD/$cfile" -o "$PWD/$filename"
+  gcc "$PWD/$cfile" -o "$PWD/$filename" 2>> $shpath/err.log
+  if [ $? -ne 0 ]; then
+    fail+=( $cfile )
+    echo -e "Compile filed." \
+            "\n============================="
+    continue
+  fi
   echo 2 3 4 5 | $PWD/$filename
   echo -e " expected: -7+22i\n"
   echo 1 0 1 0 | $PWD/$filename
@@ -67,8 +75,15 @@ do
   echo -e "============================="
 done
 
-n_efile=`ls $tfile* | grep -Ev "*.c" | wc -l`
+if [ ${#fail[@]} -gt 0 ]; then
+  echo -e "\n\n========Failed files========="
+  for failfile in ${fail[@]}; do
+    echo ${failfile}
+  done
+  echo "============================="
+fi
 
+n_efile=`ls $tfile* | grep -Ev "*.c" | wc -l`
 echo -e "\n========compile check========" \
         "\nSrc File      : $n_efile" \
         "\nExecute File  : $n_file" \
diff --git a/09/hatten9-3 b/09/hatten9-3
--- a/09/hatten9-3
+++ b/09/hatten9-3
@@ -1,5 +1,6 @@
 #!/bin/sh
 
+shpath=$PWD
 cd $(dirname $0)
 path=${1:-../src}
 cd $path
@@ -39,13 +40,20 @@ echo -e "\n==========Test case==========" \
         "\n 9.7 6.9 7 4.5 3.2 0" \
         "\n============================="
 
+fail=()
 for cfile in $tfile*.c
 do
   filename=`basename $cfile .c`
   echo -e "\n============================="
   echo "$filename"
   echo "----------------------------"
-  gcc "$PWD/$cfile" -o "$PWD/$filename"
+  gcc "$PWD/$cfile" -o "$PWD/$filename" 2>> $shpath/err.log
+  if [ $? -ne 0 ]; then
+    fail+=( $cfile )
+    echo -e "Compile filed." \
+            "\n============================="
+    continue
+  fi
   echo 1.0 1.1 3.1 1.2 2.2 4.4 | $PWD/$filename
   echo -e " expected: 3.405\n"
   echo 0.0 0.0 2.0 2.0 4.0 4.0 | $PWD/$filename
@@ -57,8 +65,15 @@ do
   echo -e "============================="
 done
 
-n_efile=`ls $tfile* | grep -Ev "*.c" | wc -l`
+if [ ${#fail[@]} -gt 0 ]; then
+  echo -e "\n\n========Failed files========="
+  for failfile in ${fail[@]}; do
+    echo ${failfile}
+  done
+  echo "============================="
+fi
 
+n_efile=`ls $tfile* | grep -Ev "*.c" | wc -l`
 echo -e "\n========compile check========" \
         "\nSrc File      : $n_efile" \
         "\nExecute File  : $n_file" \
diff --git a/09/hatten9-4 b/09/hatten9-4
--- a/09/hatten9-4
+++ b/09/hatten9-4
@@ -1,5 +1,6 @@
 #!/bin/sh
 
+shpath=$PWD
 cd $(dirname $0)
 path=${1:-../src}
 cd $path
@@ -42,13 +43,20 @@ echo -e "\n==========Test case==========" \
         "\n Taro 176 Jiro 165 Saburo 168 180" \
         "\n============================="
 
+fail=()
 for cfile in $tfile*.c
 do
   filename=`basename $cfile .c`
   echo -e "\n============================="
   echo "$filename"
   echo "----------------------------"
-  gcc "$PWD/$cfile" -o "$PWD/$filename"
+  gcc "$PWD/$cfile" -o "$PWD/$filename" 2>> $shpath/err.log
+  if [ $? -ne 0 ]; then
+    fail+=( $cfile )
+    echo -e "Compile filed." \
+            "\n============================="
+    continue
+  fi
   echo Taro 176 Jiro 165 Saburo 168 167 | $PWD/$filename
   echo -e " expected: Taro, Saburo.\n"
   echo Taro 176 Jiro 165 Saburo 168 16 | $PWD/$filename
@@ -58,8 +66,15 @@ do
   echo -e "============================="
 done
 
-n_efile=`ls $tfile* | grep -Ev "*.c" | wc -l`
+if [ ${#fail[@]} -gt 0 ]; then
+  echo -e "\n\n========Failed files========="
+  for failfile in ${fail[@]}; do
+    echo ${failfile}
+  done
+  echo "============================="
+fi
 
+n_efile=`ls $tfile* | grep -Ev "*.c" | wc -l`
 echo -e "\n========compile check========" \
         "\nSrc File      : $n_efile" \
         "\nExecute File  : $n_file" \
diff --git a/09/kihon9-1 b/09/kihon9-1
--- a/09/kihon9-1
+++ b/09/kihon9-1
@@ -1,5 +1,6 @@
 #!/bin/sh
 
+shpath=$PWD
 cd $(dirname $0)
 path=${1:-../src}
 cd $path
@@ -44,13 +45,20 @@ echo -e "\n==========Test case==========" \
         "\n 10001 Taro 900 10002 Jiro 7000 10003 Saburo 360 10003" \
         "\n============================="
 
+fail=()
 for cfile in $tfile*.c
 do
   filename=`basename $cfile .c`
   echo -e "\n============================="
   echo "$filename"
   echo "----------------------------"
-  gcc "$PWD/$cfile" -o "$PWD/$filename"
+  gcc "$PWD/$cfile" -o "$PWD/$filename" 2>> $shpath/err.log
+  if [ $? -ne 0 ]; then
+    fail+=( $cfile )
+    echo -e "Compile filed." \
+            "\n============================="
+    continue
+  fi
   echo 10001 Taro 90 10002 Jiro 70 10003 Saburo 60 10002 | $PWD/$filename
   echo -e " expected: StudentID 10002, Name Jiro, English 70.\n"
   echo 10 Ao 90 20 Shiro 70 30 Kiiro 60 20 | $PWD/$filename
@@ -62,8 +70,15 @@ do
   echo -e "============================="
 done
 
-n_efile=`ls $tfile* | grep -Ev "*.c" | wc -l`
+if [ ${#fail[@]} -gt 0 ]; then
+  echo -e "\n\n========Failed files========="
+  for failfile in ${fail[@]}; do
+    echo ${failfile}
+  done
+  echo "============================="
+fi
 
+n_efile=`ls $tfile* | grep -Ev "*.c" | wc -l`
 echo -e "\n========compile check========" \
         "\nSrc File      : $n_efile" \
         "\nExecute File  : $n_file" \
